### PR TITLE
Add explicit tagnames so types can be forward declared

### PR DESCRIPTION
**Pull request by stephenatwork**
See issue #1051

### CODE REVIEW

**Review by maxgolov — APPROVED** [review]
I approve as author of this code. Looks consistent, and should work even with older compilers.

I'd like you to wait for the current maintainers approval @lalitb

**Review by lalitb — APPROVED** [review]
LGTM.

**Comment by lalitb** [comment]
@stephenatwork - This PR looks good to merge. Can you please merge it,

**Comment by maxgolov** [comment]
We're working together with Stephen on this feature. I took the liberty to merge it :)

**Pull request merged**
