### PR TITLE
Add missing configuration value from ODWPrivacyGuardInitConfig

### PR DESCRIPTION
**Pull request by sid-dahiya**

### CODE REVIEW

**Review by lalitb — APPROVED** [review]

**Review by ThomsonTan — APPROVED** [review]
:shipit:

**Comment by guojiubo** [comment]
Hi @sid-dahiya, could we merge it and release a new iOS SDK version? Thanks!

**Comment by ThomsonTan** [comment]
@sid-dahiya is this ready to be merged?

**Comment by guojiubo** [comment]
Gentle ping.

**Comment by guojiubo** [comment]
@lalitb do we have a plan to release a new iOS SDK with this change? We have been looking forward to this for a long time.

**Pull request merged**
