### PR TITLE
Update json.hpp to v3.9.1

### LINKED ISSUE #833: json.hpp compiler errors when compiling on MSVC
When compiling `win32-lib` on MSVC, `\lib\include\mat\json.hpp` throws `warning C28020: The expression '0<=_Param_(1)&&_Param_(1)<=400-1' is not true at this call.: Lines: 14534, 14554`, which is treated as an error. 

This is a [known issue](https://github.com/nlohmann/json/pull/1969) and was fixed in [Release 3.8.0](https://github.com/nlohmann/json/releases/tag/v3.8.0) of the JSON library.

### PR DESCRIPTION
**Pull request by maxgolov**
Fixes #833

Integrate the latest Released version of json.hpp from https://github.com/nlohmann/json/releases/tag/v3.9.1

Presently following the existing process, i.e. drop-in a copy of it.

We may later on consider mapping it as submodule under `third_party`. But not in this PR.

cc: @SahilAshar

### CODE REVIEW

**Comment by maxgolov** [comment]
> spellcheck / build (pull_request) Failing after 6s — build

Oh, please................... total waste. Ignore this spell checker.

**Review by mkoscumb — APPROVED** [review]
LGTM

**Comment by maxgolov** [comment]
Ok, I'll explicitly turn off the spell checker for now for json.hpp file. Should fix the CI loop and won't resurface again.

**Comment by maxgolov** [comment]
Appears like the new version adds new subtype, and gcc is being strict now about that `/home/runner/work/cpp_client_telemetry/cpp_client_telemetry/lib/api/LogConfiguration.cpp:80:24: error: enumeration value ‘binary’ not handled in switch [-Werror=switch]
`
Will need a fix for Linux.

**Comment by maxgolov** [comment]
Converting it to draft, as it appears like there's more than one spot that needs an adjustment to make it work with the new library on Linux and Mac (Windows is already good).

**Comment by maxgolov** [comment]
Please ignore the timeout of `C/C++ CI on Windows (vs2017) / Build (pull_request) In progress — This check has started...`, appears like there is some transient issue with GitHub actions.

**Pull request merged**
