### PR TITLE
[WIP] Fix Android test loop failure on Mac

### LINKED ISSUE #901: Android build on mac is failing because of JCenter shutdown
This failure of Android build on Mac:
image

is now permanently happening.

Detailed explanation here:
https://docs.microsoft.com/en-us/appcenter/build/android/jcentershut

I was trying to workaround it for specific package here:
https://github.com/microsoft/cpp_client_telemetry/pull/895

While it fixes the first build error by disabling the linter, obviously it'd fail later for other packages. And it happens because the Android Studio on Mac version / Gradle version on Mac is old enough to try fetching from a repository that is now permanently unavailable as of May 1, 2021.

The fix would be to somehow use a newer version of Android Studio. We can also temporarily suppress the failing build. Or we could try to specify an alternate URL? I am not sure though, what other official URL we can use for the relevant Android tooling.

We can also temporarily disable the Android CI / build tests on Mac. Windows builds are still running (but tests are not running on Windows).

@larvacea @anod @reyang

### PR DESCRIPTION
**Pull request by maxgolov**
Fixes #901

JCenter shutdown: https://docs.microsoft.com/en-us/appcenter/build/android/jcentershut caused our build loops to fail.

**Changes**

Merit of all these changes is to ensure that we no longer attempt to pull anything from jcenter anymore. Thus, resolving the issue that this old artifacts repo was shutdown in May. There is no change to SDK nor NDK versions, only build tools have been upgraded.

- switch to `mavenCentral` binary artifacts repo before `jcenter` (eventually need to remove `jcenter`)
- ~~update `reactivecircus/android-emulator-runner` to latest presently available version~~
- use latest gradle tools `com.android.tools.build:gradle:4.2.0`
- use latest `gradle-6.7.1`
- use `--refresh-dependencies` flag to refetch latest versions, ignoring cache
- add equivalent to Unix test script for a Windows runner (just a dev-focused script, not used in CI)
- upgrade `buildToolsVersion` to **30.0.2**

UPDATE: the build is getting stuck due to so many things to be downloaded. I'm adding GitHub cache Action here to try speed it up.

### CODE REVIEW

**Comment by maxgolov** [comment]
@saurabh-sagrawal @larvacea - would you be able to take a look at this issue? I tried fixing the problem by upgrading to more recent set of dependencies. But it appears to be handing while starting the emulator on GitHub actions runner.

**Comment by maxgolov** [comment]
@lalitb - I think it'd make sense to at least _temporarily_ switch Android test loop on Mac. That'd unblock all other pending PRs. Since GitHub Action is really letting us down (latest AVD hangs), we could have re-enabled custom hosted runner on our own physical machine, preinstalling the necessary versions and AVD / emulator. I can give you the details of our Mac mini.

**Comment by lalitb** [comment]
> @lalitb - I think it'd make sense to at least _temporarily_ switch Android test loop on Mac. That'd unblock all other pending PRs. Since GitHub Action is really letting us down (latest AVD hangs), we could have re-enabled custom hosted runner on our own physical machine, preinstalling the necessary versions and AVD / emulator. I can give you the details of our Mac mini.

@maxgolov  - I have disabled both the failing android builds now  ( Mac and Windows ) temporarily, but looks like it will be effective for only new PRs. I can enable custom-hosted runners on physical mac once you provide more details of it. Thanks.

**Comment by maxgolov** [comment]
Your change to disable the loops should be merged in master, then all existing PRs would have to be updated to intake your change, then they'd pass.

**Comment by lalitb** [comment]
> Your change to disable the loops should be merged in master, then all existing PRs would have to be updated to intake your change, then they'd pass.

Ok. I actually disabled them through the github admin interface. Will raise a PR instead.

**Comment by lalitb** [comment]
> @saurabh-sagrawal @larvacea - would you be able to take a look at this issue? I tried fixing the problem by upgrading to more recent set of dependencies. But it appears to be handing while starting the emulator on GitHub actions runner.

@saurabh-sagrawal @larvacea - Would you be able to help us here. Thanks.

**Comment by saurabh-sagrawal** [comment]
> > @saurabh-sagrawal @larvacea - would you be able to take a look at this issue? I tried fixing the problem by upgrading to more recent set of dependencies. But it appears to be handing while starting the emulator on GitHub actions runner.
> 
> @saurabh-sagrawal @larvacea - Would you be able to help us here. Thanks.

**Comment by saurabh-sagrawal** [comment]
> > @saurabh-sagrawal @larvacea - would you be able to take a look at this issue? I tried fixing the problem by upgrading to more recent set of dependencies. But it appears to be handing while starting the emulator on GitHub actions runner.
> 
> @saurabh-sagrawal @larvacea - Would you be able to help us here. Thanks.

@lalitb sorry I'm not aware of the build process here so I'm not of much help here.
Also sorry for the mis-click from my side which closed the PR by mistake.

**Pull request closed without merging**
