### PR TITLE
Modules commit update.

### PR DESCRIPTION
**Pull request by sid-dahiya**

### CODE REVIEW

**Comment by sid-dahiya** [comment]
@maxgolov @mkoscumb is `APITest.LogManager_Reinitialize_UploadNow` test broken? I don't see why it would be failing with the modules update.

**Comment by maxgolov** [comment]
Can you please rerun it? We can trace it back to when it was broken, but I suspect the root cause is related to #848 - getting stuck on logger in use while `FlushAndTeardown` is called. We need to fix the lock guard logic to avoid a deadlock. We can probably try to more precisely pin-point what exact commit started causing it, as it was quite solid, say 6 months ago. This test is abusive and exercises the nastiest possible path, using the logger while system goes up and down. I think it MAY be Okay to temporarily comment it out.

**Review by maxgolov — APPROVED** [review]

**Comment by sid-dahiya** [comment]
> Can you please rerun it? We can trace it back to when it was broken, but I suspect the root cause is related to #848 - getting stuck on logger in use while `FlushAndTeardown` is called. We need to fix the lock guard logic to avoid a deadlock. We can probably try to more precisely pin-point what exact commit started causing it, as it was quite solid, say 6 months ago. I think it's around the `RecordShutdown` that was trying to keep loggers zombies, even if the system goes down/ This test is rather abusive and exercises the nastiest possible path, _something that customers should not do_ - using the logger while system goes up and down. I think it MAY be Okay to temporarily comment it out for now, but it'd be great to make this more fool-proof / robust. I also assume that there isn't something like registered callback from any of the live inspector or DDV that went out of scope.

I don't believe there is any DDV, PG or LiveInspector code that is impacting things here. FWIW, the test passed locally for me on two separate Windows boxes and Ubuntu WSLs on two machines. It is certainly something that is exaggerated in the Actions environments.

**Comment by sid-dahiya** [comment]
> Can you please rerun it? We can trace it back to when it was broken, but I suspect the root cause is related to #848 - getting stuck on logger in use while `FlushAndTeardown` is called. We need to fix the lock guard logic to avoid a deadlock. We can probably try to more precisely pin-point what exact commit started causing it, as it was quite solid, say 6 months ago. I think it's around the `RecordShutdown` that was trying to keep loggers zombies, even if the system goes down/ This test is rather abusive and exercises the nastiest possible path, _something that customers should not do_ - using the logger while system goes up and down. I think it MAY be Okay to temporarily comment it out for now, but it'd be great to make this more fool-proof / robust. I also assume that there isn't something like registered callback from any of the live inspector or DDV that went out of scope.

@maxgolov this seems to be a deterministic failure as I've rerun the loops a few times and it fails everytime: https://github.com/microsoft/cpp_client_telemetry/pull/869/checks?check_run_id=2578146000#step:3:2460

**Comment by maxgolov** [comment]
@sid-dahiya - any changes you do that could have been leaving a handler for Live Inspector or DDV? Because the `master` branch now shows all tests passed. Here:
https://github.com/microsoft/cpp_client_telemetry/commit/b4acb9112393968c57199cb0d4b733eba4c2482a

You can click on green checkmark to see that all tests have been passed successfully:
https://github.com/microsoft/cpp_client_telemetry/runs/2572518349

**Comment by sid-dahiya** [comment]
@maxgolov, I don't believe there are any changes in Modules that would impact this, or maybe I'm missing some subtlety here. This is the only net new change here: https://github.com/microsoft/cpp_client_telemetry_modules/commit/0176efa694b4c15f0ffafb177980f58326e74863

**Comment by maxgolov** [comment]
`
[ RUN      ] APITest.LogManager_Reinitialize_UploadNow
/Users/runner/work/cpp_client_telemetry/cpp_client_telemetry/tests/functests/APITest.cpp:1048: Failure
Expected: (shutdownSec + 1) >= (total_time), actual: 21 vs 25
`

Can you temporarily disable the test. This is something timing related, and appears like a transient failure related to possibly Mac host being too busy.

**Comment by sid-dahiya** [comment]
> `[ RUN ] APITest.LogManager_Reinitialize_UploadNow /Users/runner/work/cpp_client_telemetry/cpp_client_telemetry/tests/functests/APITest.cpp:1048: Failure Expected: (shutdownSec + 1) >= (total_time), actual: 21 vs 25`
> 
> Can you temporarily disable the test. This is something timing related, and appears like a transient failure related to possibly Mac host being too busy.

Done and opened #870.

**Comment by maxgolov** [comment]
@sid-dahiya - the rest looks good. Transient failure in re-initialize still happens in another test. It is not as frequently tripping, so I'm merging your change.

**Pull request merged**
